CocktailWebApp/Models/CocktailRepository.cs
using CocktailsLibrary;

namespace CocktailWebApp.Models
{
    public class CocktailRepository : ICocktailRepository
    {
        private ICollection<Cocktail> Cocktails { get; set; }
        public IOutputInfo outputManager;

        public CocktailRepository(IOutputInfo output)
        {
            Cocktails = new List<Cocktail>();
            this.outputManager = output;
        }

        public IEnumerable<Cocktail> GetCocktails()
        {
            return Cocktails ?? new List<Cocktail>();
        }

        public void AddCocktail(Cocktail cocktail)
        {
            if (Cocktails == null)
            {
                throw new NullReferenceException();
            }
            Cocktails.Add(cocktail);
        }

        public void SaveCocktailsInfoToTxt(string filePath)
        {
            if (Cocktails == null)
            {
                throw new NullReferenceException();
            }

            foreach (Cocktail cocktail in Cocktails)
            {
                if (cocktail != null)
                {
                    cocktail.OutputShortFile(filePath);
                    cocktail.OutputFullFile(filePath);
                }
            }
        }

    }
}

CocktailWebApp/Models/ErrorViewModel.cs
namespace CocktailWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CocktailWebApp/Models/ICocktailRepository.cs
using CocktailsLibrary;

namespace CocktailWebApp.Models
{
    public interface ICocktailRepository
    {
        public IEnumerable<Cocktail> GetCocktails();

        public void AddCocktail(Cocktail cocktail);

        public void SaveCocktailsInfoToTxt(string filePath);
    }

    public class CocktailRepository : ICocktailRepository
    {
        private ICollection<Cocktail> Cocktails { get; set; }
        public IOutputInfo outputManager;

        public CocktailRepository(IOutputInfo output)
        {
            Cocktails = new List<Cocktail>();
            this.outputManager = output;
        }

        public IEnumerable<Cocktail> GetCocktails()
        {
            return Cocktails ?? new List<Cocktail>();
        }

        public void AddCocktail(Cocktail cocktail)
        {
            if (Cocktails == null)
            {
                throw new NullReferenceException();
            }
            Cocktails.Add(cocktail);
        }

        public void SaveCocktailsInfoToTxt(string filePath)
        {
            if (Cocktails == null)
            {
                throw new NullReferenceException();
            }

            foreach (Cocktail cocktail in Cocktails)
            {
                if (cocktail != null)
                {
                    cocktail.OutputShortFile(filePath);
                    cocktail.OutputFullFile(filePath);
                }
            }
        }

    }
}

CocktailWebApp/Controllers/CocktailController.cs
using CocktailsLibrary;
using CocktailWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading;

namespace CocktailWebApp.Controllers
{
    public class CocktailController : Controller
    {
        private readonly ICocktailRepository _cocktailService;

        public CocktailController(ICocktailRepository cocktailService)
        {
            this._cocktailService = cocktailService;

            IOutputInfo printer = new OutputInfo();
            this._cocktailService.AddCocktail(new Cocktail1(printer));
            this._cocktailService.AddCocktail(new Cocktail2(printer));
        }

        public IActionResult Index()
        {
            return View(this._cocktailService.GetCocktails());
        }

        public IActionResult ExportDataToTxtFile()
        {
            string filename="cocktails.txt";
            try
            {
                if (!System.IO.File.Exists(filename))
                {
                    System.IO.File.Create(filename).Close();
                }
                else
                {
                    System.IO.File.WriteAllText(filename, string.Empty);
                }

                this._cocktailService.SaveCocktailsInfoToTxt(filename);
            }
            catch (Exception ex)
            {
                return BadRequest($"Failed to create file: {ex.Message}");
            }

            var fileName = "cocktails.txt";
            var mimeType = "text/plain";

            var fileBytes = System.IO.File.ReadAllBytes(filename);
            return File(fileBytes, mimeType, fileName);
        }
    }
}

CocktailWebApp/Controllers/HomeController.cs
using CocktailWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CocktailWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CocktailWebApp/Views/Cocktail/Index.cshtml
@model IEnumerable<CocktailsLibrary.Cocktail>


@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShortInfo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullInfo)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.Raw(item.ShortInfo)</td>
                <td>@Html.Raw(item.FullInfo)</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="ExportDataToTxtFile">Download info about cocktails (txt file)</a>

CocktailWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CocktailWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CocktailWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CocktailWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CocktailWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocktail" asp-action="Index">Cocktails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CocktailWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>